name: Build Go Project for Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [amd64, arm64, 386]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # Ersetze mit der gewünschten Go-Version

      - name: Build Binary
        run: |
          go mod tidy
          env GOARCH=${{ matrix.arch }} go build -o wishlist-windows-${{ matrix.arch }}.exe .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wishlist-windows-${{ matrix.arch }}
          path: | 
            wishlist-windows-${{ matrix.arch }}.exe
